name: CI Package

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     
     - name: npm install, build, and test
       run: |
         npm install
         npm run build
         npm run package

     - name: Archive production artifacts
       uses: actions/upload-artifact@v3
       with:
         name: vsix
         path: |
           *.vsix
